# Generated by Django 2.1.15 on 2021-05-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0002_auto_20210518_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titre',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
