# Generated by Django 2.1.15 on 2021-05-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0009_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='date_creation',
            field=models.DateTimeField(),
        ),
    ]
