# Generated by Django 2.1.15 on 2021-05-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0010_auto_20210521_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='contenu',
            field=models.CharField(max_length=300),
        ),
    ]
